server:
  port: 8084

spring:
  application:
    name: live-tip-mock-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mock:
  tip:
    qps: 500

logging:
  level:
    com.live.tip: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
